In [1]:
import torch

In [2]:
x = torch.rand(3)

In [3]:
print(x)

tensor([0.0292, 0.9059, 0.0421])


In [4]:
x = torch.ones(2,2,dtype=torch.float16)

In [5]:
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [6]:
x = torch.tensor([2.5,0.1])

In [7]:
print(x)

tensor([2.5000, 0.1000])


In [8]:
torch.cuda.is_available()

True

In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [10]:
x

tensor([[0.0248, 0.0380],
        [0.3821, 0.2310]])

In [11]:
y

tensor([[0.9177, 0.6656],
        [0.3233, 0.1366]])

In [12]:
z = x + y

In [13]:
z

tensor([[0.9425, 0.7035],
        [0.7054, 0.3676]])

In [14]:
z = torch.add(x,y)

In [15]:
z

tensor([[0.9425, 0.7035],
        [0.7054, 0.3676]])

In [16]:
y.add_(x)

tensor([[0.9425, 0.7035],
        [0.7054, 0.3676]])

In [17]:
z = x-y

In [18]:
z

tensor([[-0.9177, -0.6656],
        [-0.3233, -0.1366]])

In [19]:
z = torch.sub(x,y)

In [20]:
z

tensor([[-0.9177, -0.6656],
        [-0.3233, -0.1366]])

In [21]:
y.sub_(x)

tensor([[0.9177, 0.6656],
        [0.3233, 0.1366]])

In [22]:
z = x*y
z

tensor([[0.0228, 0.0253],
        [0.1235, 0.0316]])

In [23]:
z = torch.mul(x,y)
z

tensor([[0.0228, 0.0253],
        [0.1235, 0.0316]])

In [24]:
z = x/y
z

tensor([[0.0271, 0.0570],
        [1.1817, 1.6910]])

In [25]:
z = torch.div(x,y)
z

tensor([[0.0271, 0.0570],
        [1.1817, 1.6910]])

In [26]:
x = torch.rand(5,3)

In [27]:
x

tensor([[0.5013, 0.3529, 0.9754],
        [0.8124, 0.6763, 0.4115],
        [0.6985, 0.4745, 0.1659],
        [0.7479, 0.7199, 0.2653],
        [0.2755, 0.7127, 0.4174]])

In [28]:
x[:,0]

tensor([0.5013, 0.8124, 0.6985, 0.7479, 0.2755])

In [29]:
import numpy as np

In [30]:
a = torch.ones(5)

In [31]:
a

tensor([1., 1., 1., 1., 1.])

In [32]:
b = a.numpy()

In [33]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [34]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [35]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [36]:
b = torch.from_numpy(a)

In [37]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [38]:
a += 1
a

array([2., 2., 2., 2., 2.])

In [39]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z = z.to("cpu")

In [41]:
x = torch.ones(5,requires_grad=True)

In [42]:
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

# AutoGrad

In [43]:
import torch
x = torch.rand(3)
print(x)

tensor([0.1194, 0.6512, 0.4818])


In [44]:
x = torch.rand(3,requires_grad=True)

In [45]:
print(x)

tensor([0.5735, 0.7938, 0.0968], requires_grad=True)


In [46]:
y = x+2
print(y)

tensor([2.5735, 2.7938, 2.0968], grad_fn=<AddBackward0>)


In [48]:
print(x.grad)

None


In [49]:
z = y*y*2
print(z)

tensor([13.2457, 15.6108,  8.7931], grad_fn=<MulBackward0>)


In [50]:
z = z.mean()

In [51]:
print(z)

tensor(12.5499, grad_fn=<MeanBackward0>)


In [52]:
z.backward()

In [53]:
print(x.grad)

tensor([3.4313, 3.7251, 2.7957])


In [54]:
# prevent tracking gradient

In [55]:
#x.requires_grad_(False)

tensor([0.5735, 0.7938, 0.0968])

In [56]:
#x.detach()

tensor([0.5735, 0.7938, 0.0968])

In [58]:
#with torch.no_grad():

In [59]:
import torch
x = torch.randn(3,requires_grad=True)

In [60]:
x

tensor([ 0.4587,  1.6983, -0.5973], requires_grad=True)

In [61]:
x.requires_grad_(False)

tensor([ 0.4587,  1.6983, -0.5973])

In [62]:
y = x.detach()
y

tensor([ 0.4587,  1.6983, -0.5973])

In [63]:
with torch.no_grad():
    y = x+2
    print(y)

tensor([2.4587, 3.6983, 1.4027])


In [64]:
# example 1

In [65]:
import torch
weights = torch.ones(4,requires_grad=True)
print(weights)

tensor([1., 1., 1., 1.], requires_grad=True)


In [68]:
for epoch in range(1):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights)

tensor([6., 6., 6., 6.])
tensor([1., 1., 1., 1.], requires_grad=True)


In [69]:
# through optimizer

In [73]:
import torch
weights = torch.ones(4,requires_grad=True)
optimizer = torch.optim.SGD([weights],lr=0.01)
optimizer.step()
optimizer.zero_grad

<bound method Optimizer.zero_grad of SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)>

In [77]:
# Back Propagation

In [78]:
import torch
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)

In [79]:
# forward pass

In [80]:
y_hat = w*x
loss = (y_hat-y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [81]:
# backward pass

In [82]:
loss.backward()
print(w.grad)

tensor(-2.)


In [9]:
import tensorflow as tf

In [12]:
tf.__version__

'2.6.2'

In [14]:
torch.version.cuda

'11.1'

In [ ]:
!nvid