In [1]:
import torch
import torchvision
from torch.utils.data import DataLoader,Dataset
import numpy as np
import math

In [4]:
class WineDataset(Dataset):
    def __init__(self):
        xy = np.loadtxt('wine.csv',delimiter=",",dtype=np.float32,skiprows=1)
        self.x = torch.from_numpy(xy[:,1:])
        self.y = torch.from_numpy(xy[:,[0]])
        self.n_samples = xy.shape[0]
    def __getitem__(self,index):
        return self.x[index],self.y[index]
    def __len__(self):
        return self.n_samples

In [5]:
dataset = WineDataset()

In [6]:
first_data = dataset[0]

In [7]:
first_data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [8]:
features, labels = first_data
print(features)
print(labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])


In [9]:
# DataLoader
dataloader = DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=2)

In [10]:
dataiter = iter(dataloader)

In [11]:
dataiter

In [12]:
data = dataiter.next()

In [13]:
data

[tensor([[1.4390e+01, 1.8700e+00, 2.4500e+00, 1.4600e+01, 9.6000e+01, 2.5000e+00,
          2.5200e+00, 3.0000e-01, 1.9800e+00, 5.2500e+00, 1.0200e+00, 3.5800e+00,
          1.2900e+03],
         [1.3360e+01, 2.5600e+00, 2.3500e+00, 2.0000e+01, 8.9000e+01, 1.4000e+00,
          5.0000e-01, 3.7000e-01, 6.4000e-01, 5.6000e+00, 7.0000e-01, 2.4700e+00,
          7.8000e+02],
         [1.3820e+01, 1.7500e+00, 2.4200e+00, 1.4000e+01, 1.1100e+02, 3.8800e+00,
          3.7400e+00, 3.2000e-01, 1.8700e+00, 7.0500e+00, 1.0100e+00, 3.2600e+00,
          1.1900e+03],
         [1.3410e+01, 3.8400e+00, 2.1200e+00, 1.8800e+01, 9.0000e+01, 2.4500e+00,
          2.6800e+00, 2.7000e-01, 1.4800e+00, 4.2800e+00, 9.1000e-01, 3.0000e+00,
          1.0350e+03]]),
 tensor([[1.],
         [3.],
         [1.],
         [1.]])]

In [14]:
features,labels = data
print(features)
print(labels)

tensor([[1.4390e+01, 1.8700e+00, 2.4500e+00, 1.4600e+01, 9.6000e+01, 2.5000e+00,
         2.5200e+00, 3.0000e-01, 1.9800e+00, 5.2500e+00, 1.0200e+00, 3.5800e+00,
         1.2900e+03],
        [1.3360e+01, 2.5600e+00, 2.3500e+00, 2.0000e+01, 8.9000e+01, 1.4000e+00,
         5.0000e-01, 3.7000e-01, 6.4000e-01, 5.6000e+00, 7.0000e-01, 2.4700e+00,
         7.8000e+02],
        [1.3820e+01, 1.7500e+00, 2.4200e+00, 1.4000e+01, 1.1100e+02, 3.8800e+00,
         3.7400e+00, 3.2000e-01, 1.8700e+00, 7.0500e+00, 1.0100e+00, 3.2600e+00,
         1.1900e+03],
        [1.3410e+01, 3.8400e+00, 2.1200e+00, 1.8800e+01, 9.0000e+01, 2.4500e+00,
         2.6800e+00, 2.7000e-01, 1.4800e+00, 4.2800e+00, 9.1000e-01, 3.0000e+00,
         1.0350e+03]])
tensor([[1.],
        [3.],
        [1.],
        [1.]])


In [15]:
#training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples,n_iterations)

178 45


In [16]:
for epoch in range(num_epochs):
    for i,(inputs,labels) in enumerate(dataloader):
        if (i+1)%1==0:
            print(f'epoch {epoch+1}/{num_epochs}, step {i+1}/{n_iterations},inputs {inputs.shape}')

epoch 1/2, step 1/45,inputs torch.Size([4, 13])
epoch 1/2, step 2/45,inputs torch.Size([4, 13])
epoch 1/2, step 3/45,inputs torch.Size([4, 13])
epoch 1/2, step 4/45,inputs torch.Size([4, 13])
epoch 1/2, step 5/45,inputs torch.Size([4, 13])
epoch 1/2, step 6/45,inputs torch.Size([4, 13])
epoch 1/2, step 7/45,inputs torch.Size([4, 13])
epoch 1/2, step 8/45,inputs torch.Size([4, 13])
epoch 1/2, step 9/45,inputs torch.Size([4, 13])
epoch 1/2, step 10/45,inputs torch.Size([4, 13])
epoch 1/2, step 11/45,inputs torch.Size([4, 13])
epoch 1/2, step 12/45,inputs torch.Size([4, 13])
epoch 1/2, step 13/45,inputs torch.Size([4, 13])
epoch 1/2, step 14/45,inputs torch.Size([4, 13])
epoch 1/2, step 15/45,inputs torch.Size([4, 13])
epoch 1/2, step 16/45,inputs torch.Size([4, 13])
epoch 1/2, step 17/45,inputs torch.Size([4, 13])
epoch 1/2, step 18/45,inputs torch.Size([4, 13])
epoch 1/2, step 19/45,inputs torch.Size([4, 13])
epoch 1/2, step 20/45,inputs torch.Size([4, 13])
epoch 1/2, step 21/45,inputs 