In [1]:
import torch
import torch.nn as nn
import numpy as np


In [2]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)

In [3]:
x=  np.array([2.0,1.0,0.1])

In [4]:
outputs = softmax(x)

In [5]:
print('softmax numpy:' ,outputs)

softmax numpy: [0.65900114 0.24243297 0.09856589]


In [6]:
x = torch.tensor([2.0,1.0,0.1])

In [7]:
outputs = torch.softmax(x,dim=0)

In [8]:
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [9]:
# Cross Entropy

In [12]:
#y = [1,0,0]
#y_hat = [0.7,0.2,0.1]
#y = [1,0,0]
#y_hat = [0.1,0.3,0.6]

In [13]:
import torch
import torch.nn as nn
import numpy as np

In [14]:
def cross_entropy(actual,predicted):
    loss = -np.sum(actual*np.log(predicted))
    return loss

In [16]:
y = np.array([1,0,0])

In [17]:
y_pred_good = np.array([0.7,0.2,0.1])
y_pred_bad = np.array([0.1,0.3,0.6])

In [18]:
l1 = cross_entropy(y,y_pred_good)

In [19]:
l1

0.35667494393873245

In [20]:
l2 = cross_entropy(y,y_pred_bad)

In [21]:
l2

2.3025850929940455

In [23]:
# Pytorch

In [24]:
loss = nn.CrossEntropyLoss()

In [25]:
y = torch.tensor([0])

In [26]:
y

tensor([0])

In [27]:
y_pred_good = torch.tensor([[2.0,1.0,0.1]])
y_pred_bad = torch.tensor([[0.5,2.0,0.3]])

In [28]:
l1 = loss(y_pred_good,y)

In [29]:
l1

tensor(0.4170)

In [30]:
l2 = loss(y_pred_bad,y)

In [31]:
l2

tensor(1.8406)

In [32]:
print(l1.item())

0.4170299470424652


In [33]:
print(l2.item())

1.840616226196289


In [34]:
_,prediction1 = torch.max(y_pred_good,1)

In [35]:
_,prediction2 = torch.max(y_pred_bad,1)

In [36]:
prediction1

tensor([0])

In [37]:
prediction2

tensor([1])

In [1]:
############################################

In [2]:
import torch 
import torch.nn as nn
import numpy as np

In [3]:
def softmax(x):
    return np.exp(x)/np.sum(np.sum(np.exp(x),axis=0))

In [4]:
x = np.array([2.0,1.0,0.1])
outputs = softmax(x)
print(outputs)

[0.65900114 0.24243297 0.09856589]


In [6]:
x = torch.tensor([2.0,1.0,0.1])
outputs = torch.softmax(x,dim=0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [7]:
# crossentropy

In [8]:
def crossentropy(actual,predicted):
    EPS = 1e-15
    predicted = np.clip(predicted,EPS,1-EPS)
    loss = -np.sum(actual*np.log(predicted))
    return loss

In [9]:
y = np.array([1,0,0])

In [10]:
y_pred_good = np.array([0.7,0.2,0.1])
y_pred_bad = np.array([0.1,0.3,0.6])

In [11]:
l1 = crossentropy(y,y_pred_good)
l2 = crossentropy(y,y_pred_bad)
print(l1)
print(l2)

0.35667494393873245
2.3025850929940455


In [12]:
#################### Pytorch ####################

In [13]:
loss = nn.CrossEntropyLoss()

In [14]:
y = torch.tensor([0])

In [15]:
y_pred_good = torch.tensor([[2.0,1.0,0.1]])
y_pred_bad = torch.tensor([[0.5,2.0,0.3]])

In [16]:
l1 = loss(y_pred_good,y)

In [17]:
l2 = loss(y_pred_bad,y)

In [18]:
print(l1)
print(l2)

tensor(0.4170)
tensor(1.8406)


In [19]:
# get predictions

In [20]:
x,predictions1 = torch.max(y_pred_good,1)

In [21]:
x

tensor([2.])

In [22]:
predictions1

tensor([0])

In [23]:
# Batch size = 3

In [24]:
y = torch.tensor([2,0,1])

In [25]:
y_pred_good = torch.tensor(
[[0.1,0.2,3.9],
[1.2,0.1,0.3],
[0.3,2.2,0.2]])

In [26]:
y_pred_bad = torch.tensor(
[[0.9,0.2,0.1],
[0.1,0.3,1.5],
[1.2,0.2,0.5]])

In [27]:
l1 = loss(y_pred_good,y)

In [28]:
l2 = loss(y_pred_bad,y)

In [29]:
print(l1)
print(l2)

tensor(0.2834)
tensor(1.6418)


In [30]:
_,predictions1 = torch.max(y_pred_good,1)
_,predictions2 = torch.max(y_pred_bad,1)
print(f'Actual class:{y},y_pred1:{predictions1},y_pred2:{predictions2}')

Actual class:tensor([2, 0, 1]),y_pred1:tensor([2, 0, 1]),y_pred2:tensor([0, 2, 0])
